spring:
  application:
    name: ArquiteturaSpring
  jpa:
    show-sql: true
  main:
    lazy-initialization: false

app:
  automaker:
    common-engine: 130
  config:
    variable: Value of variable
    value1: 500